### ISSUE TITLE
Use canonical libyaml repo

### ISSUE THREAD

**Issue by ingydotnet** [rsimoes/Alien-LibYAML#1]
Hi. The canonical and maintained repo for libyaml is at https://github.com/yaml/libyaml

It is mirrored from Kirill's svn repo, and he is aware of it. It has a 1.2 branch that is undergoing dev. This is the source for YAML::XS and Ruby's Psych.

**Comment by rsimoes** [comment]
I'm downloading a release build, though, as opposed to checking out from a repository. Is there a canonical location for that?

**Comment by rsimoes** [comment]
Switching to downloading the tgz of the github mirror master branch, either permanently or until a better location is identified.
