### ISSUE TITLE
Support 5.8?

### ISSUE THREAD

**Issue by plicease** [rsimoes/Alien-LibYAML#4]
Is there a reason that you are requiring Perl 5.10?

Personally can't wait for 5.8 to die, however, AB does support 5.8 and I think that Alien::LibYAML could as well.

**Comment by rsimoes** [comment]
It really has more to do with my unwillingness to spend time troubleshooting v5.8 issues. I can at least do a trial release that supports v5.8 and see what happens. If no new issues crop up, I'll do a full release.

As a side note, I think the main thing that prevents 5.8's death is CPAN authors' continued support of it.

**Comment by plicease** [comment]
I think most of any trouble is going to happen in AB rather than A::LibYAML.  AB is committed to support 5.8 as long as the rest of the tool chain does, so you shouldn't be too much on the hook.

**Comment by plicease** [comment]
I see you gave me comaint on Alien::LibYAML, ::GMP and ::Autotools, I assume you don't mind if I cut a new release then?
